Feature issue75 article how to
worldclub-sokuniv/xeory_base_child pull request #80
Opened 2020-08-07 09:07 UTC by yuu772

## Related issue
No: #75 

## What is an issue
< describe what is issue >
how to 記事のテーマ作成

## How to solve it
< describe How to solve the issue >
・to doリストのデザイン作成
・目次のページ内ジャンプ機能追加

## Cnsiderable affects
< describe considerable affects on other programs>
![preview_SSA](https://user-images.githubusercontent.com/64079253/89629399-b8039700-d8d8-11ea-9643-d6a5822b7c1f.png)
![preview1_local](https://user-images.githubusercontent.com/64079253/89629406-bafe8780-d8d8-11ea-9922-508d251c9a21.png)
![preview2_local](https://user-images.githubusercontent.com/64079253/89629410-bd60e180-d8d8-11ea-8f90-f8ef3ba2db81.png)

![preview4_local](https://user-images.githubusercontent.com/64079253/89629429-c2259580-d8d8-11ea-9722-d163a7d82a0d.png)

![preview3_local](https://user-images.githubusercontent.com/64079253/89629421-bfc33b80-d8d8-11ea-9f1b-ad943a2bef23.png)
1枚目は本番環境でのプレビューの結果です。
2枚目以降はスタイルが反映された後のプレビューです。

2020-08-07 13:36 UTC, mmfiber commented on styles/_howto.scss
> +.post-content {
これは全てのページに影響を与えないですか？
他のページも.post-content を持っている気がします。

2020-08-07 13:38 UTC, mmfiber commented on styles/_howto.scss
> +.child {
.child は自分で作ったと思うのですが認識はあっていますか？
もしそうであれば、この名前は抽象的すぎます。

＜改善案＞

- 名前にもっと情報を込める
- あまり意味のないがCSSのセレクタ のためだけに欲しいのであれば擬似要素を使う

2020-08-07 13:39 UTC, mmfiber commented on styles/_howto.scss
> +      content: "" !important;
□ではなくユニコードで指定してください

2020-08-07 13:40 UTC, mmfiber commented on styles/_howto.scss
> +  border: solid 2px skyblue;
色はカラーのsass ファイルがあるのでそちらに定義してください

2020-08-17 08:44 UTC, yuu772 commented on styles/_howto.scss
> +.post-content {
こちらの解決策としては、ブロックエディタのブロック１つ１つにdiv要素でクラスを指定するという方法で良いでしょうか？

2020-08-17 08:45 UTC, yuu772 commented on styles/_howto.scss
> +.child {
変更後、.child-list-pointingにしようと考えていますが、適切でしょうか？

2020-08-25 09:06 UTC, mmfiber commented on styles/_howto.scss
> +.post-content {
いいえ。インタビューのデザインを参考にしてください。カテゴリーの名前が入ったクラスが自動で生成されるのでそれをセレクターに使ってください。
https://github.com/worldclub-sokuniv/xeory_base_child/blob/2ce8970b00a184fa88673ddae90e3bd7260ac206/styles/_interview.scss#L1

2020-08-26 06:05 UTC, yuu772 commented on styles/_howto.scss
> +.post-content {
回答ありがとうございます。post-contentで指定していたものを削除しても影響がなかったので、削除しました。
マージして頂いてもよろしいでしょうか？

2020-08-27 10:26 UTC, mmfiber reviewed
セレクタ を強くしてください。
例えば、今後他のところで `to-do` というクラスを使ったらどうなりますか？

2020-09-14 13:36 UTC, yuu772 commented on styles/_howto.scss
> +.post-content {
> セレクタ を強くしてください。

post-content > div.to-do はどうでしょうか？動作確認済です

2020-09-15 03:22 UTC, mmfiber commented on styles/_howto.scss
> +.post-content {
ありがとうございます。今回のように提案ベースで案をもらえると回答しやすいです。

結論から言うとまだ弱いですね。理由は以下の通りです。

* 今のところ how-to のみに適応させたい
* post-content はすべてのページに存在する
* 他のページにもdiv.to-doは存在する可能性はある

鍵となるのは、**how-to ページのみ**に適応させることです。

2020-09-15 06:29 UTC, yuu772 commented on styles/_howto.scss
> +.post-content {
ありがとうございます。
interviewと同様、

.howto-category{
   post-content > div.to-do
}

で合っていますでしょうか？こちらも動作確認済みです

2020-09-19 08:21 UTC, mmfiber commented on styles/_howto.scss
> +.post-content {
あっています

2020-09-20 05:57 UTC, mmfiber commented
@yuu772 
commit push しましたか？

2020-09-20 07:07 UTC, yuu772 commented
push出来ていませんでした！すみません。
今push したので、確認よろしくお願いします。

2020-09-20 08:10 UTC, mmfiber requested changes
important が多いという印象です。important は最終手段だと思ってください。important 以外の方法で修正可能ですか？

2020-09-21 02:57 UTC, yuu772 commented
セレクタの強さを調節したことで、importantを使わずに済みました。
確認よろしくおねがいします。

2020-09-23 01:26 UTC, mmfiber approved these changes
LGTM!

2020-09-23 01:27 UTC, merged