Feature issue46 new category page
worldclub-sokuniv/xeory_base_child pull request #85
Opened 2020-09-20 17:07 UTC by Satosei111997

## Related issue
No: #46

## What is an issue
カテゴリーページの刷新

## How to solve it

## Cnsiderable affects

2020-09-20 17:08 UTC, Satosei111997 commented
このようなものになりました。
![Screen Shot 2020-09-21 at 2 07 44](https://user-images.githubusercontent.com/63938631/93717233-590b9000-fbaf-11ea-938b-5762a693e9a9.png)

2020-09-23 01:32 UTC, mmfiber commented on categories/normal.php
> +	<!-- <body style="background-image: url(https://worldclub-soka.com/wp-content/uploads/2020/09/color-2174065-1.png);" class="background-image"> -->
削除してください

2020-09-23 01:32 UTC, mmfiber commented on categories/normal.php
> +		<!-- <div class="main-content"> -->
削除してください

2020-09-23 01:42 UTC, mmfiber requested changes

2020-09-23 01:42 UTC, mmfiber commented on categories/normal.php
> +	<!-- <body style="background-image: url(https://worldclub-soka.com/wp-content/uploads/2020/09/color-2174065-1.png);" class="background-image"> -->
削除してください

2020-09-23 01:42 UTC, mmfiber commented on categories/normal.php
> +		<!-- <div class="main-content"> -->
削除してください

2020-09-23 01:42 UTC, mmfiber commented on categories/normal.php
> +				<!-- <section class="cat-content">
基本的にコメントアウトではなく削除でお願いします。

2020-09-23 01:42 UTC, mmfiber commented on categories/normal.php
> +								<?php } ?>
質問

ここはサムネイルがないときどうなりますか？

2020-09-23 01:42 UTC, mmfiber commented on categories/normal.php
> +				</div>
これ必要ですか？

2020-09-23 01:42 UTC, mmfiber commented on categories/normal.php
> +			<div id="side" <?php bzb_layout_side(); ?> role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
質問
role, itemscope, itemtype のそれぞれの役割を教えてください

2020-09-23 01:42 UTC, mmfiber commented on sidebar.php
> -<!-- <div id="side" <?php bzb_layout_side(); ?> role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
ここのコードはcategory/normal.php と重複していますね。どちらかで一方で他方のコードを読み込むようにしてください。

2020-09-23 01:42 UTC, mmfiber commented on styles/_category.scss
> +article.page, article.wp101,
`article.wp101` と article.seo101 は特定の記事のみに適用されるのではないでしょうか？このセレクタの意図はなんでしょう？

2020-09-23 01:42 UTC, mmfiber commented on styles/_interview.scss
> -    @include responsive-img(80%);
こちら修正前と修正後の変化がみたいです

2020-09-28 02:55 UTC, Satosei111997 commented on categories/normal.php
> +				<!-- <section class="cat-content">
ここはタグ検索の部分で一応コメントアウトしておくという話だったかと思いますが、消してしまって大丈夫ですか？

2020-10-12 03:35 UTC, Satosei111997 commented
画像サイズの修正と画像がない場合のno imageの挿入をfront pageにも適応しました。

![Screen Shot 2020-10-12 at 12 34 20](https://user-images.githubusercontent.com/63938631/95702452-51f41100-0c87-11eb-9301-425a111a033a.png)
![Screen Shot 2020-10-12 at 12 34 14](https://user-images.githubusercontent.com/63938631/95702460-56b8c500-0c87-11eb-8380-067c748d4ca4.png)

2020-10-19 04:42 UTC, Satosei111997 commented
縦長の画像には対応しないので、記事では横長の画像しか使わないようにすること
スマホ画面↓
![Screen Shot 2020-10-19 at 13 40 28](https://user-images.githubusercontent.com/63938631/96402442-dd821a80-1210-11eb-9855-8009cc66dd06.png)

2020-10-19 08:56 UTC, mmfiber commented
@Satosei111997 
もう一度修正コメントを見直し、対応お願いします

2020-11-02 07:50 UTC, Satosei111997 commented
@mmfiber 対応いたしました！

2020-11-03 07:42 UTC, mmfiber approved these changes

2020-11-23 04:06 UTC, merged